#!/usr/bin/env sh
# Assess Build Image

set -e

# clean any existing test suite files
rm -rf /tmp/official-images

# docker images test suite
git clone --depth 1 https://github.com/docker-library/official-images.git /tmp/official-images

# assess image
/tmp/official-images/test/run.sh -c /tmp/official-images/test/config.sh \
    -t debian-apt-get \
    -t gcc-c-hello-world \
    -t gcc-cpp-hello-world \
  "${DOCKER_IMAGE:-ashenm/baseimage:latest}"

# clean test suite files
rm -rf /tmp/official-images
