version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: src/latest
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: src/developer
    schedule:
      interval: weekly
